[package]
name = "crates_and_packages"
version = "0.1.0"
edition = "2021"

[lib]
name = "wbc"
path = "src/lib.rs"

[[bin]]
name = "test"
path = "src/main.rs"

[[bin]]
name = "new-test"
path = "src/main.rs"
